<?xml version="1.0" encoding="utf-8"?><Database Name="MIT" Class="OperationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=w3jwslbp5n.database.windows.net;Initial Catalog=MIT;User ID=mit" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MITConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Publisher" Member="Publishers">
    <Type Name="Publisher">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="Publisher_BOOK" Member="BOOKs" ThisKey="Id" OtherKey="PublisherId" Type="BOOK" />
    </Type>
  </Table>
  <Table Name="dbo.BOOK" Member="BOOKs">
    <Type Name="BOOK">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="PublisherId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="NChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="StockLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BOOK_Order" Member="Orders" ThisKey="Id" OtherKey="BookId" Type="Order" />
      <Association Name="Publisher_BOOK" Member="Publisher" ThisKey="PublisherId" OtherKey="Id" Type="Publisher" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerReferenceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BOOK_Order" Member="BOOK" ThisKey="BookId" OtherKey="Id" Type="BOOK" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerReferenceId" OtherKey="ReferenceId" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="ReferenceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="ReferenceId" OtherKey="CustomerReferenceId" Type="Order" />
    </Type>
  </Table>
</Database>